name: Deploy via FTP (Locaweb)

on:

  push:

    branches: [ main ]

jobs:

  web-deploy:

    name: Deploy

    runs-on: ubuntu-latest

    steps:

    
uses: actions/checkout@v4

     with: fetch-depth: 2

    
name: FTP-Deploy to Locaweb

      uses: locaweb/ftp-deploy@1.0.0

      with:

        server: ${{ secrets.HOST }} 

        username: ${{ secrets.USER }}

        password: ${{ secrets.PASS }}

        server-dir: public/

        local-dir: html-version/ 

        # IMPORTANTE: 

        # local-dir deve ser o nome da pasta com o código estático (ex: html-version/)

        # server-dir deve ser o diretório raiz da sua hospedagem (geralmente public_html/)
